`How to Fast-track` page removed
sora-xor/sora-docs pull request #167
Opened 2023-08-18 12:17 UTC by bgodlin

2023-08-19 12:19 UTC, Tieumsan approved these changes

2023-08-21 10:29 UTC, WRRicht3r requested changes

2023-08-21 10:29 UTC, WRRicht3r commented on src/guides/governance/fast-track-public-voting.md
> +This page is no more accessible.
```suggestion
This page is no longer accessible.
```

2023-08-21 13:17 UTC, WRRicht3r approved these changes

2023-08-21 13:17 UTC, merged