Improve synths pages
sora-xor/sora-docs pull request #224
Opened 2023-12-18 11:17 UTC by bgodlin

2023-12-18 11:37 UTC, WRRicht3r requested changes

2023-12-18 11:37 UTC, WRRicht3r commented on src/xst.md
> +Consequently, you can swap those assets. You can swap XOR to XSTUSD and vice-versa like that:
```suggestion
Consequently, you can swap those assets. This is how to swap XOR to XSTUSD and vice-versa:
```

2023-12-18 12:11 UTC, outoftardis approved these changes
please address William's comment, and it's all good

2023-12-20 11:21 UTC, WRRicht3r requested changes

2023-12-20 11:21 UTC, WRRicht3r commented on src/xst.md
> +In the meantime, you can find XSTUSD on [Polkaswap](https://polkaswap.io/). The XST asset id is `0x0200090000000000000000000000000000000000000000000000000000000000`. You can also access all synthetic
```suggestion
In the meantime, you can find XSTUSD on [Polkaswap](https://polkaswap.io/). The XST asset id is `0x0200090000000000000000000000000000000000000000000000000000000000`. You can also access all synthetic assets on Polkaswap by visiting the [wallet page](https://polkaswap.io/#/wallet) and activating the `Show only synthetic tokens` flag in the user interface, as per the screen below:
```

2023-12-20 11:21 UTC, WRRicht3r commented on src/xst.md
> +Consequently, you can swap those assets. This is how to swap XOR to XSTUSD and vice-versa:
```suggestion
You can also swap those assets. This is how to swap XOR to XSTUSD and vice-versa:
```

2023-12-20 12:45 UTC, WRRicht3r approved these changes

2023-12-22 09:57 UTC, merged