TBC docs small readability improvements
sora-xor/sora-docs pull request #245
Opened 2024-01-23 05:24 UTC by bragov4ik

Minor fixes for better readability

2024-01-30 11:30 UTC, WRRicht3r requested changes

2024-01-30 11:30 UTC, WRRicht3r commented on src/tbc.md
> +The implication of this scenario is that the Sell-Price Function of the token bonding curve is not 20% lower than the Buy-Price Function (as it should be in the **ideal scenario)**, but it is even le
```suggestion
This scenario implies that the Sell-Price Function of the token bonding curve is not 20% lower than the Buy-Price Function (as it should be in the **ideal scenario**), but it is even lower. There is little liquidity in the reserves for you to sell your XOR tokens, and the price on the Sell-Price Function may be low compared to the secondary market price.
```

2024-02-01 10:40 UTC, outoftardis approved these changes

2024-02-21 15:50 UTC, WRRicht3r approved these changes

2024-03-04 06:43 UTC, merged