Added Polkadot cross-chain transfer guide
sora-xor/sora-docs pull request #246
Opened 2024-01-23 20:32 UTC by bgodlin

2024-01-30 11:35 UTC, WRRicht3r requested changes

2024-01-30 11:35 UTC, WRRicht3r commented on src/substrate-bridge.md
> +This section showcases various scenarios for bidirectional transfers between SORA mainnet and Polkadot.
```suggestion
This section showcases various scenarios for bidirectional transfers between the SORA mainnet and Polkadot.
```

2024-01-30 11:35 UTC, WRRicht3r commented on src/substrate-bridge.md
> +To transfer assets from Polkadot to the SORA network, additional to the `XOR` for the SORA network transaction, you will need to hold `DOT` tokens to pay for the Kusama network transaction fees.
```suggestion
To transfer assets from Polkadot to the SORA network, in addition to the `XOR` for the SORA network transaction, you will need to hold `DOT` tokens to pay the Polkadot network transaction fees.
```

2024-01-30 11:35 UTC, WRRicht3r commented on src/substrate-bridge.md
> +  - The `Parachain` is `2035`
```suggestion
  - The `Parachain` is `2025`
```

2024-01-30 11:35 UTC, WRRicht3r commented on src/substrate-bridge.md
> +  - The `Parachain` is `2035`
Isn't the SORA Polkadot parachain ID 2025?

2024-01-30 11:35 UTC, WRRicht3r commented on src/substrate-bridge.md
> +  - The `X1:XCMV3Junction` is `Accountid32` and in the `id:[u8:32]` section, input your SORA network account address (as the recipient of the to transfer)
```suggestion
  - The `X1:XCMV3Junction` is `Accountid32`, and in the `id:[u8:32]` section, input your SORA network account address (as the recipient of the transfer)
```

2024-01-30 11:35 UTC, WRRicht3r commented on src/substrate-bridge.md
> +  - In the field `Fungible:Compact<128>` add the number of tokens to be transferred. You have to add ten zeroes after the amount.
```suggestion
  - In the field `Fungible:Compact<128>` add the number of tokens to be transferred. **You have to add ten zeroes after the amount**.
```

2024-01-30 11:35 UTC, WRRicht3r commented on src/substrate-bridge.md
> +Finally, submit the transaction and sign on the pop-up using your password. After the transaction is successful, you will notice your `DOT` balance is reduced in Kusama and has increased proportional
```suggestion
Finally, submit the transaction and sign on the pop-up using your password. After the successful transaction, you will notice your `DOT` balance is reduced in Polkadot and has increased proportionally in your SORA account. Now, let’s test a transaction in the opposite direction;
```

2024-01-30 11:35 UTC, WRRicht3r commented on src/substrate-bridge.md
> +- Finally, enter the desired `amount` to be sent. You have to add eighteen zeroes after the amount.
```suggestion
- Finally, enter the desired `amount` to be sent. **You have to add eighteen zeroes after the amount**.
```

2024-01-30 11:35 UTC, WRRicht3r commented on src/substrate-bridge.md
> +Then, submit the transaction and sign on the pop-up using your password. After the transaction is successful, you will notice your `KSM` balance is reduced in the SORA network and increased in Kusama
```suggestion
Then, submit the transaction and sign on the pop-up using your password. After the successful transaction, you will notice your `DOT` balance is reduced in the SORA network and increased in Polkadot.
```

2024-01-30 12:16 UTC, outoftardis commented on src/substrate-bridge.md
> +  - Select version is `V3`
```suggestion
  - The version is `V3`
```


```suggestion
  - For the version select `V3`
```

2024-02-22 12:28 UTC, WRRicht3r approved these changes

2024-02-27 13:15 UTC, outoftardis approved these changes

2024-02-29 08:02 UTC, merged