Add files via upload
sora-xor/sora-docs pull request #249
Opened 2024-01-31 16:35 UTC by Tieumsan

2024-02-01 09:17 UTC, WRRicht3r requested changes

2024-02-01 09:17 UTC, WRRicht3r commented on src/adding-tokens-to-hashi-bridge.md
> +3. Copy the preimage hash of the preimage you have just created and submit a proposal in _Governance > Democracy_. Alternatively you can try to reach out to a council member for the Council to direct
```suggestion
3. Copy the preimage hash of your created preimage and submit a proposal in _Governance > Democracy_. Alternatively, you can reach out to a council member for the Council to directly create a motion to add the asset to the bridge with the preimage you created. This will fast-track the process of adding the asset to the bridge.
```

2024-02-01 09:17 UTC, WRRicht3r commented on src/adding-tokens-to-hashi-bridge.md
> +5. The RPC will return a bunch of hashes. These are off-chain request hashes, the last one should be `OutgoingAddAsset` request. To find out if the asset was added successfully, use the `getRequests`
```suggestion
5. The RPC will return a bunch of hashes. These are off-chain request hashes; the last one should be the `OutgoingAddAsset` request. To determine if the asset was added successfully, use the `getRequests` RPC.
```

2024-02-01 09:17 UTC, WRRicht3r commented on src/adding-tokens-to-hashi-bridge.md
> +6. After your hash is found, use `getApprovedRequests` RPC to get the approvals.
```suggestion
6. After finding your hash, use the `getApprovedRequests` RPC to get the approvals.
```

2024-02-01 15:30 UTC, outoftardis commented on src/adding-tokens-to-hashi-bridge.md
> +4. Once the proposal goes through, acquire the bridge’s peers' signatures via the `ethBridge.getAccountRequests` RPC with your account as the first argument and status `ApprovalsReady`.
```suggestion
4. Once the proposal goes through, acquire the signatures of the bridge’s peers via the `ethBridge.getAccountRequests` RPC with your account as the first argument and status `ApprovalsReady`.
```

2024-02-07 18:04 UTC, WRRicht3r approved these changes

2024-02-07 18:06 UTC, outoftardis approved these changes

2024-02-07 23:19 UTC, merged