SORA WIKI Translation to Spanish by Rubrum
sora-xor/sora-docs pull request #265
Opened 2024-04-14 22:44 UTC by javitoarroba

Review by javitoarroba

2024-04-16 16:20 UTC, WRRicht3r requested changes
En su mayoría los cambios necesarios son quitar las imágenes. Se puede usar la sección CN como referencia de lo que se necesita en cuanto a contenido. 
Muchas gracias por su grandioso esfuerzo!

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/bridgeTransferKusamaToSora.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/bridgeTransferPolkadotToSora.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/bridgeTransferSoraToKusama.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/bridgeTransferSoraToPolkadot.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/createOrderBook.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/createdLimitOrderQuery.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/createdLimitOrderResult.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/fundsReceivedOnParachain.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/ken-burn-extrinsics.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/orderBookCreated.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/placeLimitOrder.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/sidechain-token-registration.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/substrate-bridge-components.svg
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/thischain-token-registration.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/token-burn.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/transfer-to-parachain.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/xcmMessageDispatchedOnMainnet.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-16 16:20 UTC, WRRicht3r commented on src/es/assets/xcmMessageSent.png
Por favor quitar las imágenes que aparecen duplicadas

2024-04-18 10:25 UTC, WRRicht3r approved these changes

2024-04-24 10:53 UTC, WRRicht3r approved these changes

2024-05-02 13:08 UTC, outoftardis approved these changes

2024-05-03 09:54 UTC, merged