Create new token description
sora-xor/sora-docs pull request #282
Opened 2024-06-20 14:39 UTC by AndreyKortosov

Added description of new tokens: PUSSY, KXOR, KARMA

2024-06-20 14:50 UTC, WRRicht3r commented on src/karma.md
> +      content: Chameleon pool, liquidity providers in the XOR-ETH pool, buy-back and burn mechanizm, distributed to the Demeter farm, deflationary mechanism
Here you would add a summary of the content of the page, not just the keywords

2024-06-20 15:10 UTC, WRRicht3r requested changes

2024-06-20 15:10 UTC, WRRicht3r commented on src/karma.md
> +      content: Chameleon pool, liquidity providers in the XOR-ETH pool, buy-back and burn mechanizm, distributed to the Demeter farm, deflationary mechanism
```suggestion
      content: The KARMA token provides farming rewards to liquidity providers in the XOR-ETH pool on Polkaswap. It is specifically designed to incentivize liquidity providers and support the stability of the Chameleon pools on Polkaswap.
```

2024-06-20 15:10 UTC, WRRicht3r commented on src/karma.md
> +KARMA is a key token in the SORA ecosystem, specifically designed to incentivize liquidity providers and support the stability of the Chameleon pools on Polkaswap. Here's a detailed look at how KARMA
```suggestion
KARMA is a key SORA ecosystem token, specifically designed to incentivize liquidity providers and support the stability of the Chameleon pools on Polkaswap. Here's a detailed look at how KARMA works.
```

2024-06-20 15:10 UTC, WRRicht3r commented on src/karma.md
> +By participating in liquidity provision, users are rewarded with KARMA, encouraging more liquidity in the Chameleon pools.
```suggestion
By participating in liquidity provision for this pool, users are rewarded with KARMA, encouraging more liquidity in the Chameleon pools.
```

2024-06-20 15:10 UTC, WRRicht3r commented on src/karma.md
> +This buy-back-and-burn mechanism helps to regulate the supply of KARMA, supporting its value.
```suggestion
This buy-back-and-burn mechanism helps regulate the KARMA supply, supporting its value.
```

2024-06-20 15:10 UTC, WRRicht3r commented on src/karma.md
> +KARMA also has a deflationary mechanism. For every 10 million XOR burned, 1 KARMA token is minted.
Will more Karma be minted after the initial distribution? or is this describing the burn drop mechanism?

2024-06-20 15:10 UTC, WRRicht3r commented on src/karma.md
> +## In summary
Please start the article with the summary

2024-06-20 15:10 UTC, WRRicht3r commented on src/kxor.md
> +      content: Learn about KENSETSU, Pegged to XOR, swap for ETH in the XOR-ETH pool, buy-back mechanizm, buring KEN, burning TBCD
```suggestion
      content: Learn about Kensetsu XOR (KXOR), a robust and flexible financial tool, pegged to the price of XOR that supports the growth and stability of the SORA ecosystem.  
```

2024-06-20 15:10 UTC, WRRicht3r commented on src/kxor.md
> +## Pegged to XOR
you can remove this subheader and add the next sentence to the intro

2024-06-20 15:10 UTC, WRRicht3r commented on src/kxor.md
> +- 1% is allocated for buying back and burning the Chameleon Token, a new token in the ecosystem.
is this PUSSY?

2024-06-20 15:10 UTC, WRRicht3r commented on src/kxor.md
> +## Integration with PUSSY Tokens
Add a hyperlink to the PUSSY page

2024-06-20 15:10 UTC, WRRicht3r commented on src/pussy.md
> +# PUSSY :cat:
A nice cat image would be good

2024-06-20 15:10 UTC, WRRicht3r commented on src/pussy.md
> +      content: Learn about PUSSY, reward builders, mint Kensetsu XOR (KXOR)
```suggestion
      content: Learn about the PUSSY token, a dedicated cryptocurrency designed to fund and reward builders within our community
```

2024-06-20 15:10 UTC, WRRicht3r commented on src/pussy.md
> +The PUSSY token is a dedicated cryptocurrency designed to fund and reward builders within our community. Here’s an overview of its purpose and functionality
```suggestion
The PUSSY token is a dedicated cryptocurrency designed to fund and reward builders within the SORA community. Here’s an overview of its purpose and functionality
```

2024-06-20 15:10 UTC, WRRicht3r commented on src/pussy.md
> +The PUSSY token is created specifically to support builders working on productive outputs and projects within the SORA ecosystem.
```suggestion
The PUSSY token supports builders working on productive outputs and projects within the SORA ecosystem.
```

2024-06-25 16:40 UTC, WRRicht3r requested changes

2024-06-25 16:40 UTC, WRRicht3r commented on src/kxor.md
> +- 1% is allocated for buying back and burning the Chameleon Token, a new token in the ecosystem.
```suggestion
- 1% is allocated for buying back and burning the Chameleon Token, a new token in the ecosystem proposed by the community.
```

2024-06-25 16:40 UTC, WRRicht3r commented on src/kxor.md
> +This process ensures that PUSSY tokens are used productively and enhances the overall utility of the tokens within the ecosystem.
```suggestion
This process ensures that tokens are used productively and enhances the overall utility of the tokens within the ecosystem. The asset used currently is the PUSSY token.
```

2024-06-25 16:40 UTC, WRRicht3r commented on src/kxor.md
> +Builders can lock their PUSSY tokens in a Kensetsu vault to mint KXOR.
```suggestion
Builders can lock their tokens in a Kensetsu vault to mint KXOR.
```

2024-06-25 16:40 UTC, WRRicht3r commented on src/pussy.md
> +The PUSSY token is a dedicated cryptocurrency in the SORA community, aimed at funding and rewarding builders. It plays a crucial role in the ecosystem by ensuring builders are compensated for their e
```suggestion
The PUSSY token is a dedicated meme cryptocurrency in the SORA economy aimed at funding and rewarding builders. Its role in the ecosystem is to ensure builders are compensated for their efforts and can convert their earnings into a stable and valuable asset.
```

2024-06-27 10:18 UTC, AndreyKortosov commented on src/karma.md
> +KARMA also has a deflationary mechanism. For every 10 million XOR burned, 1 KARMA token is minted.
No, no more Karma will be minted. The users have the opportunity to mint Karma via burn XOR until June 06.

2024-06-27 10:18 UTC, AndreyKortosov commented on src/kxor.md
> +- 1% is allocated for buying back and burning the Chameleon Token, a new token in the ecosystem.
No

2024-06-27 12:39 UTC, WRRicht3r approved these changes

2024-06-27 12:40 UTC, WRRicht3r requested changes

2024-06-27 12:40 UTC, WRRicht3r commented on src/karma.md
> +KARMA also has a deflationary mechanism. For every 10 million XOR burned, 1 KARMA token is minted.
```suggestion
KARMA also has a deflationary mechanism. During the initial mint, which ended on June 6th, for every 10 million XOR burned, 1 KARMA token was minted.
```

2024-06-27 12:43 UTC, WRRicht3r approved these changes

2024-06-27 12:44 UTC, merged