Introduction VXOR
sora-xor/sora-docs pull request #312
Opened 2024-10-25 16:24 UTC by AndreyKortosov

I need add picture to the article

2024-10-26 10:04 UTC, WRRicht3r commented
Hi, why is the file empty?
Also, the token logo is available [here](https://github.com/sora-xor/sora-branding/blob/master/tokens/SORA/svg/vXOR.svg)

2024-10-26 16:47 UTC, AndreyKortosov commented
@WRRicht3r Hi
Good question, I've re-pushed the article

2024-11-04 10:31 UTC, WRRicht3r requested changes

2024-11-04 10:31 UTC, WRRicht3r commented on src/vxor.md
> +# Key Features:
```suggestion
## Key Features:
```

2024-11-04 10:31 UTC, WRRicht3r commented on src/vxor.md
> +- Vesting Mechanism with Buy-Back-and-Burn: The VXOR mechanism uses 99% of the daily remint of XOR to buy back and burn VXOR, reducing supply and increasing value for vested participants. This mechan
```suggestion
- A vesting Mechanism with Buy-Back-and-Burn: The VXOR mechanism uses 99% of the daily remint of XOR to buy back and burn VXOR, reducing supply and increasing value for vested participants. This mechanism essentially acts as a vesting tool to reward long-term holders.
```

2024-11-04 10:31 UTC, WRRicht3r commented on src/vxor.md
> +- Encouraging Economic Expansion: Weekly calculations of the general price trend for XOR influence VXOR rewards. A positive trend results in additional VXOR being given to VXOR stakers and XOR-VXOR L
```suggestion
- Economic Expansion Encouragement: Weekly calculations of the general price trend for XOR influence VXOR rewards. A positive trend results in additional VXOR being given to VXOR stakers and XOR-VXOR LP farmers. This mechanism is designed to align rewards with the growth in XOR’s market performance, encouraging builders and XOR-using countries to actively support SORA’s token economy.
```

2024-11-04 10:31 UTC, WRRicht3r commented on src/vxor.md
> +# In Summary
```suggestion
## In Summary
```

2024-11-04 10:31 UTC, WRRicht3r commented on src/vxor.md
> +# More Details
```suggestion
## More Details
```

2024-11-04 10:31 UTC, WRRicht3r commented on src/vxor.md
> +# Key Features:
Only one H1 per page please

2024-11-05 14:44 UTC, WRRicht3r approved these changes

2024-11-05 14:44 UTC, merged