Review markup and fix images
sora-xor/sora-docs pull request #36
Opened 2023-05-19 13:31 UTC by outoftardis

This PR mostly contains the following changes:

- Fixed markup/punctuation
- Added steps for procedures
- Added todo comments
- For images:
  - Renamed image files to give them more meaningful names (not for all images)
  - Removed duplicates
  - Centered and minimized images in docs (not for all images)
  - Checked that the image was relevant to the text it was accompanying (100% for renamed images, can't say the same for all the other).

I did review the doc contents and in some places changed the phrasing a bit, but it was a secondary focus.

2023-05-19 13:45 UTC, WRRicht3r requested changes

2023-05-19 13:45 UTC, WRRicht3r commented on src/advanced-trading.md
>  You can get the error saying "**Not enough liquidity**". It's important to understand what this means.
```suggestion
It is possible to get an error saying "**Not enough liquidity**" and understanding what this means is important.
```

2023-05-19 13:45 UTC, WRRicht3r commented on src/check-supply.md
> +    353.0005 kXOR = 353 000.5 XOR (including XOR on Ethereum network)
```suggestion
    353.0005 kXOR = 353 000.5 XOR (including XOR on the Ethereum network)
```

2023-05-19 13:45 UTC, WRRicht3r commented on src/consensus.md
> +If you’re interested in helping secure the future of SORA and Polkaswap, and earning rewards in the process, read more [here](https://medium.com/sora-xor/how-to-run-a-sora-testnet-node-a4d42a9de1af).
Can we link this to the wiki article we have on running a node?

2023-05-22 11:08 UTC, outoftardis commented on src/consensus.md
> +If you’re interested in helping secure the future of SORA and Polkaswap, and earning rewards in the process, read more [here](https://medium.com/sora-xor/how-to-run-a-sora-testnet-node-a4d42a9de1af).
sure, I'll change the link

2023-05-22 18:37 UTC, WRRicht3r approved these changes

2023-05-22 19:10 UTC, bgodlin approved these changes

2023-05-22 19:50 UTC, merged