XST Platform documentation
sora-xor/sora-docs pull request #42
Opened 2023-05-29 10:05 UTC by pakrentos

# Changes
- Added `xst-platform.md`
- Added xst-platform link in `config.ts`

2023-05-29 11:27 UTC, outoftardis commented on .vitepress/config.ts
> -          { text: "XST", link: "tba" },
should we delete the `tba.md` file?

2023-05-29 11:32 UTC, outoftardis commented on src/xst-platform.md
> +$F_{XOR}$ - fee amount in XOR
I suggest making it a table

```suggestion
|      Notation      |                                Description                                |
| ------------------ | ------------------------------------------------------------------------- |
| $S_f$              | Fee ratio associated with the selected synthetic asset                    |
| $S_o$              | Rate of the oracle symbol associated with the selected synthetic asset    |
| $B_p^b$            | Reference buy price of the base synthetic asset in reference asset units  |
| $B_p^s$            | Reference sell price of the base synthetic asset in reference asset units |
| $\overline{R_p^b}$ | Reference buy price of the reference asset in XOR units                   |
| $\overline{R_p^s}$ | Reference sell price of the reference asset in XOR units                  |
| $O$                | Output amount                                                             |
| $I$                | Input amount                                                              |
| $F_{XOR}$          | Fee (in XOR)                                                              |
```

2023-05-29 12:32 UTC, pakrentos commented on .vitepress/config.ts
> -          { text: "XST", link: "tba" },
It is still referenced by other entries

2023-05-30 14:23 UTC, bgodlin requested changes

2023-05-30 14:23 UTC, bgodlin commented on src/xst-platform.md
> +```mermaid
Am I the only one who is viewing the diagrams in code format instead of as visual figures? If not, we should consider finding a solution. As a reference, you can check the approach I'm experimenting with in a different branch (https://github.com/sora-xor/sora-docs/blob/3ee3b1fa6294c482fe5d2b7da24e1d06fd556689/src/substrate-bridge.md?plain=1#L5), where I included both the generated PlantUML image and the corresponding PlantUML code. I'm curious to hear your thoughts on this matter @outoftardis @pakrentos.

2023-05-30 14:23 UTC, bgodlin commented on src/xst-platform.md
> +$B_p^b = \frac{\overline{R_p^b}}{\overline{B_p^s}}$
Furthermore, I've noticed that Vitepress doesn't support TEX code. Therefore, we'll need to find a workaround. After conducting some quick research, I discovered that embeds can work, such as using

```
![equation](http://www.sciweavers.org/tex2img.php?eq=1%2Bsin%28mc%5E2%29&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=)
```

However, this solution seems cumbersome. @outoftardis have you faced this issue before?

2023-06-05 08:28 UTC, pakrentos commented on src/xst-platform.md
> +$B_p^b = \frac{\overline{R_p^b}}{\overline{B_p^s}}$
I have added plugins for KaTeX and mermaid support. Is it ok @bgodlin?

2023-06-05 11:15 UTC, outoftardis commented on src/xst-platform.md
> +```mermaid
Personally I like mermaid better than PlantUML, I think it's easier to maintain.

2023-08-11 10:45 UTC, bgodlin commented
resolves https://github.com/sora-xor/sora2-network/issues/439

2023-08-11 12:04 UTC, bgodlin commented
@aeremburg please apply the SEO tags once you are available

2023-08-15 12:49 UTC, bgodlin requested changes
Please add the missing contents for:

- [ ] https://github.com/sora-xor/sora2-network/issues/553
- [ ] https://github.com/sora-xor/sora2-network/issues/541
- [ ] Frontrunning

2023-08-15 12:49 UTC, bgodlin commented on src/synthetics.md
> +### Extrinsics
Including the names of the extrinsics that need to be called would be a valuable addition.

2023-08-18 11:03 UTC, bgodlin commented
@Tieumsan let's consider adding a table containing definitions for synthetic assets

2023-08-22 11:35 UTC, bgodlin approved these changes

2023-08-22 12:03 UTC, WRRicht3r requested changes

2023-08-22 12:03 UTC, WRRicht3r commented on src/synthetics.md
> +**Access to Global Markets**: Synthetic assets allow users to gain exposure to a wide range of traditional and digital assets from different global markets. Users can invest in assets that may otherw
```suggestion
- **Access to Global Markets**: Synthetic assets allow users to gain exposure to a wide range of traditional and digital assets from different global markets. Users can invest in assets that may otherwise be inaccessible due to geographical or regulatory limitations.
```

2023-08-22 12:03 UTC, WRRicht3r commented on src/synthetics.md
> +**Financial Inclusion**: Synthetic assets can contribute to financial inclusion by providing individuals with limited access to traditional financial services an opportunity to participate in global
```suggestion
- **Financial Inclusion**: Synthetic assets can contribute to financial inclusion by providing individuals with limited access to traditional financial services an opportunity to participate in global markets and investment opportunities.
```

2023-08-22 12:03 UTC, WRRicht3r commented on src/synthetics.md
> +**Lower Barriers to Entry**: Synthetic assets eliminate certain barriers to entry that exist in traditional financial markets. Users can start trading with lower capital requirements, fractional owne
```suggestion
- **Lower Barriers to Entry**: Synthetic assets eliminate certain barriers to entry that exist in traditional financial markets. Users can start trading with lower capital requirements, fractional ownership options, and reduced transaction costs compared to traditional asset trading.
```

2023-08-22 12:03 UTC, WRRicht3r commented on src/synthetics.md
> +**Lower Barriers to Entry**: Synthetic assets eliminate certain barriers to entry that exist in traditional financial markets. Users can start trading with lower capital requirements, fractional owne
```suggestion
- **Lower Barriers to Entry**: Synthetic assets eliminate certain barriers to entry that exist in traditional financial markets. Users can start trading with lower capital requirements, fractional ownership options, and reduced transaction costs compared to traditional asset trading.
```

2023-08-22 12:03 UTC, WRRicht3r commented on src/synthetics.md
> +**Trading Opportunities**: Synthetic assets provide users with additional trading opportunities, allowing them to capitalise on market trends, price differentials, or arbitrage opportunities. Users c
```suggestion
- **Trading Opportunities**: Synthetic assets provide users with additional trading opportunities, allowing them to capitalise on market trends, price differentials, or arbitrage opportunities. Users can engage in leveraged trading or explore complex trading strategies.
```

2023-08-22 12:03 UTC, WRRicht3r commented on src/synthetics.md
> +**Diversification**: Synthetic assets enable users to diversify their investment portfolios by gaining exposure to a variety of asset classes, such as stocks, commodities, indices, or currencies.
```suggestion
- **Diversification**: Synthetic assets enable users to diversify their investment portfolios by gaining exposure to a variety of asset classes, such as stocks, commodities, indices, or currencies.
```

2023-08-22 12:32 UTC, WRRicht3r requested changes
Hi @bgodlin could you please fix the issue with the meta header? Thanks!

2023-08-22 13:07 UTC, WRRicht3r approved these changes

2023-08-22 13:14 UTC, merged