Add staking on fearless and intro page for participating
sora-xor/sora-docs pull request #59
Opened 2023-06-14 12:01 UTC by outoftardis

Closes #57

2023-06-14 12:05 UTC, WRRicht3r requested changes

2023-06-14 12:05 UTC, WRRicht3r commented on src/participate.md
> +In this section you will find guidance on how to:
```suggestion
In this section you will find all the information you need to:
```

2023-06-14 12:09 UTC, WRRicht3r approved these changes

2023-06-14 12:25 UTC, merged

2023-06-19 08:59 UTC, bgodlin commented
@WRRicht3r @outoftardis It seems that I may have missed the merge of this pull request. I'm curious about the rationale behind including this tutorial here instead of adding it into the documentation platform of Fearless (https://wiki.fearlesswallet.io/). Instead of duplicating the tutorial in our documentation, we could simply reference the original source, maintaining a better context and focus within our overall documentation.