Pallets page. First contribution
sora-xor/sora-docs pull request #88
Opened 2023-06-23 10:06 UTC by bgodlin

2023-06-23 10:12 UTC, WRRicht3r requested changes

2023-06-23 10:12 UTC, WRRicht3r commented on src/pallets.md
> +In the context of SORA, pallets play a crucial role in the development of the SORA Network and its associated applications. SORA is a decentralized autonomous economy (DAE) built on the [Substrate](h
```suggestion
In the context of SORA, pallets play a crucial role in the development of the network and its associated applications. SORA is a decentralized autonomous economy (DAE) built on the [Substrate](https://substrate.io/) framework, and it utilizes Substrate's [pallets](https://docs.substrate.io/learn/welcome-to-substrate/) to implement its specific functionalities and features.
```

2023-06-23 11:31 UTC, outoftardis commented on src/pallets.md
> +By leveraging Substrate's pallets, SORA can customize its blockchain [runtime](https://docs.substrate.io/learn/runtime-development/) to meet its unique requirements and design principles. The pallets
```suggestion
By leveraging Substrate's pallets, SORA can customize its blockchain [runtime](https://docs.substrate.io/learn/runtime-development/) to meet its unique requirements and design principles. The pallets enable SORA to incorporate key functionalities such as token management, decentralized governance, bridges to other networks, liquidity provision, and more.
```

2023-06-23 11:31 UTC, outoftardis commented on src/pallets.md
> +- For the SORA Parachain, the Rust documentation is available at https://github.com/sora-xor/sora2-parachain.
```suggestion
To delve deeper into the connection between pallets and SORA, developers can also refer to the [Rust documentation (rustdoc)](https://docs.rs/) for the SORA pallets. Currently, there are two Rust projects being developed: [SORA Mainnet](https://github.com/sora-xor/sora2-network) and [SORA Parachain](https://github.com/sora-xor/sora2-parachain).
```

or if you want to preserve the list:
 
```suggestion
To delve deeper into the connection between pallets and SORA, developers can also refer to the [Rust documentation (rustdoc)](https://docs.rs/) for the SORA pallets. Currently, there are two Rust projects being developed: SORA Mainnet and SORA Parachain. Each project has its own dedicated repository:

- [SORA Mainnet](https://github.com/sora-xor/sora2-network)
- [SORA Parachain](https://github.com/sora-xor/sora2-parachain)
```

2023-06-27 11:42 UTC, outoftardis approved these changes

2023-06-28 12:36 UTC, WRRicht3r requested changes

2023-06-28 12:36 UTC, WRRicht3r commented on src/pallets.md
> +By leveraging Substrate's pallets, SORA can customize its blockchain [runtime](https://docs.substrate.io/learn/runtime-development/) to meet its unique requirements and design principles. The pallets
```suggestion
By leveraging Substrate's pallets, SORA can customize its blockchain [runtime](https://docs.substrate.io/learn/runtime-development/) to meet its unique requirements and design principles. These pallets enable SORA to incorporate key functions such as token management, decentralized governance, bridges to other networks, liquidity provision, and more.
```

2023-06-28 12:47 UTC, WRRicht3r approved these changes

2023-06-29 08:51 UTC, merged