94 consider restructuring the guides section
sora-xor/sora-docs pull request #96
Opened 2023-07-04 13:52 UTC by bgodlin

2023-07-04 14:00 UTC, outoftardis commented on src/id.md
>  ## Register an Identity
thus then should be level 3 heading, same for other sections that are within the "via polkadot" section 


```suggestion
### Register an Identity
```

2023-07-04 14:04 UTC, outoftardis approved these changes

2023-07-05 13:24 UTC, WRRicht3r requested changes

2023-07-05 13:24 UTC, WRRicht3r commented on .vitepress/config.ts
> +            text: "Explore Ecosystem",
```suggestion
            text: "Explore the Ecosystem",
```

2023-07-05 13:24 UTC, WRRicht3r commented on src/advanced-trading.md
>  Polkaswap's technical design allows using different liquidity sources for trading. At the moment Polkaswap supports two liquidity sources:
Soon we will have to add the XST platform

2023-07-05 13:24 UTC, WRRicht3r commented on src/check-supply.md
>  Please consider that you would see the **total supply** (this includes locked tokens and the circulating supply) of all tokens in the network and not only the **circulating** supply of the tokens.
```suggestion
Please be aware that you would see the **total supply** (this includes locked tokens and the circulating supply) of all tokens in the network and not only the **circulating** supply of the tokens.
```

2023-07-05 13:24 UTC, WRRicht3r commented on src/fast-track-public-voting.md
> +**Step 3**: Ask SORA Council to Vote
```suggestion
**Step 3**: Ask the SORA Council to Vote
```

2023-07-05 13:24 UTC, WRRicht3r commented on src/fast-track-public-voting.md
> +**Step 6**: Ask SORA Technical Committee to Vote
```suggestion
**Step 6**: Ask the SORA Technical Committee to Vote
```

2023-07-05 13:27 UTC, WRRicht3r approved these changes

2023-07-05 13:30 UTC, merged